// import { portofolioType } from "@/types/portofolio.type";
// export const portofolioData: portofolioType[] = [
//     {
//         id: 1,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "medi_care_mobile_app",
//         category: {id:1, name:"Mobile App"},
//         created_at: 2023,
//         name: "MediCare Mobile App",
//         description: "A healthcare application for online doctor consultations and medical record management.",
//         techStack: [
//             { id: 1, name: "React Native" },
//             { id: 2, name: "Node.js" },
//             { id: 3, name: "Firebase" },
//         ],
//         client_name: "Medicare Group",
//     },
//     {
//         id: 2,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "techcorp_ecommerce_platform",
//         category: {id:2, name:"Web Design & Development"},
//         created_at: 2022,
//         name: "TechCorp E-commerce Platform",
//         description: "B2B e-commerce platform with an integrated inventory management system.",
//         techStack: [
//             { id: 1, name: "Next.js" },
//             { id: 2, name: "Express.js" },
//             { id: 3, name: "MongoDB" },
//         ],
//         client_name: "TechCorp Indonesia",
//     },
//     {
//         id: 3,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "greenfood_brand_identity",
//         category: {id:3, name:"Brand Identity Design"},
//         created_at: 2024,
//         name: "GreenFood Brand Identity",
//         description: "Rebranding for organic food companies with a focus of sustainability.",
//         techStack: [
//             { id: 1, name: "Adobe Illustrator" },
//             { id: 2, name: "Adobe Photoshop" },
//             { id: 3, name: "Figma" },
//             { id: 4, name: "Canva" },
//         ],
//         client_name: "GreenFood Co.",
//     },
//     {
//         id: 4,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "financeflow_dashboard",
//         category: {id:2, name:"Web Design & Development"},
//         created_at: 2023,
//         name: "FinanceFlow Dashboard",
//         description: "Dashboard analytics for startup fintech with complex data visualization.",
//         techStack: [
//             { id: 1, name: "React" },
//             { id: 2, name: "Tailwind CSS" },
//             { id: 3, name: "Node.js" },
//             { id: 4, name: "D3.js" },
//         ],
//         client_name: "FinanceFlow Corp.",
//     },
//     {
//         id: 5,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "edulearn_learning_platform",
//         category: {id:2, name:"Web Design & Development"},
//         created_at: 2022,
//         name: "EduLearn Learning Platform",
//         description: "Online learning platform with interactive live streaming and quiz features.",
//         techStack: [
//             { id: 1, name: "React" },
//             { id: 2, name: "Node.js" },
//             { id: 3, name: "MongoDB" },
//             { id: 4, name: "Socket.io" },
//             { id: 5, name: "AWS" },
//         ],
//         client_name: "EduLearn Indonesia",
//     },
//     {
//         id: 6,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "fittracker_mobile_app",
//         category: {id:1, name:"Mobile App"},
//         created_at: 2023,
//         name: "FitTracker Mobile App",
//         description: "Fitness Tracking Application with AI Personal Trainer and Community.",
//         techStack: [
//             { id: 1, name: "Flutter" },
//             { id: 2, name: "Node.js" },
//             { id: 3, name: "MongoDB" },
//             { id: 4, name: "Socket.io" },
//             { id: 5, name: "AWS" },
//         ],
//         client_name: "FitLife",
//     },
//     {
//         id: 7,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "boostbiz_seo_campaign",
//         category: {id:4, name:"SEO & Digital Marketing"},
//         created_at: 2024,
//         name: "BoostBiz SEO Campaign",
//         description: "Comprehensive SEO and digital marketing campaign for small businesses.",
//         techStack: [
//             { id: 1, name: "Google Ads" },
//             { id: 2, name: "Facebook Ads" },
//             { id: 3, name: "SEO" },
//             { id: 4, name: "Content Marketing" },
//             { id: 5, name: "Email Marketing" },
//         ],
//         client_name: "BoostBiz",
//     },
//     {
//         id: 8,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "ux_research_ecommerce",
//         category: {id:5, name:"UX Research & Consulting"},
//         created_at: 2024,
//         name: "User Experience Research for E-commerce",
//         description: "In-depth UX research and analysis for improving e-commerce platforms.",
//         techStack: [
//             { id: 1, name: "User Interviews" },
//             { id: 2, name: "Usability Testing" },
//             { id: 3, name: "Figma" },
//             { id: 4, name: "Adobe XD" },
//         ],
//         client_name: "E-commerce Inc.",
//     },
//     {
//         id: 9,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "brand_identity_travelmate",
//         category: {id:3, name:"Brand Identity Design"},
//         created_at: 2023,
//         name: "TravelMate Brand Identity",
//         description: "Creating a fresh brand identity for a travel agency focusing on adventure tourism.",
//         techStack: [
//             { id: 1, name: "Adobe Illustrator" },
//             { id: 2, name: "Adobe Photoshop" },
//             { id: 3, name: "Figma" },
//             { id: 4, name: "Canva" },
//         ],
//         client_name: "TravelMate",
//     },
//     {
//         id: 10,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "foodiefinds_mobile_app",
//         category: {id:1, name:"Mobile App"},
//         created_at: 2022,
//         name: "FoodieFinds Mobile App",
//         description: "A social dining app that connects food enthusiasts and local eateries.",
//         techStack: [
//             { id: 1, name: "React Native" },
//             { id: 2, name: "Node.js" },
//             { id: 3, name: "Firebase" },
//         ],
//         client_name: "FoodieFinds LLC",
//     },
//     {
//         id: 11,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "healthplus_digital_marketing",
//         category: {id:4, name:"SEO & Digital Marketing"},
//         created_at: 2023,
//         name: "HealthPlus Digital Marketing",
//         description: "Digital marketing strategy and execution for a healthcare services provider.",
//         techStack: [
//             { id: 1, name: "Google Ads" },
//             { id: 2, name: "SEO" },
//             { id: 3, name: "Content Marketing" },
//             { id: 4, name: "Social Media Marketing" },
//         ],
//         client_name: "HealthPlus",
//     },
//     {
//         id: 12,
//         thumbnailUrl: "/images/working.jpg",
//         thumbnailId: "fintech_app_ux_overhaul",
//         category: {id:5, name:"UX Research & Consulting"},
//         created_at: 2022,
//         name: "FinTech App UX Overhaul",
//         description: "Comprehensive UX research and redesign for a fintech mobile application.",
//         techStack: [
//             { id: 1, name: "User Interviews" },
//             { id: 2, name: "Usability Testing" },
//             { id: 3, name: "Figma" },
//             { id: 4, name: "Adobe XD" },
//         ],
//         client_name: "FinTech Inc.",
//     }
// ]