import { portofolioType } from "@/types/portofolio.type";
export const portofolioData: portofolioType[] = [
    {
        id: 1,
        image: "/images/working.jpg",
        type: "Mobile App",
        year: 2023,
        title: "MediCare Mobile App",
        description: "A healthcare application for online doctor consultations and medical record management.",
        techStack: [
            { id: 1, name: "React Native" },
            { id: 2, name: "Node.js" },
            { id: 3, name: "Firebase" },
        ],
        client: "Medicare Group",
    },
    {
        id: 2,
        image: "/images/working.jpg",
        type: "Web Design & Development",
        year: 2022,
        title: "TechCorp E-commerce Platform",
        description: "B2B e-commerce platform with an integrated inventory management system.",
        techStack: [
            { id: 1, name: "Next.js" },
            { id: 2, name: "Express.js" },
            { id: 3, name: "MongoDB" },
        ],
        client: "TechCorp Indonesia",
    },
    {
        id: 3,
        image: "/images/working.jpg",
        type: "Brand Identity Design",
        year: 2024,
        title: "GreenFood Brand Identity",
        description: "Rebranding for organic food companies with a focus of sustainability.",
        techStack: [
            { id: 1, name: "Adobe Illustrator" },
            { id: 2, name: "Adobe Photoshop" },
            { id: 3, name: "Figma" },
            { id: 4, name: "Canva" },
        ],
        client: "GreenFood Co.",
    },
    {
        id: 4,
        image: "/images/working.jpg",
        type: "Web Design & Development",
        year: 2023,
        title: "FinanceFlow Dashboard",
        description: "Dashboard analytics for startup fintech with complex data visualization.",
        techStack: [
            { id: 1, name: "React" },
            { id: 2, name: "Tailwind CSS" },
            { id: 3, name: "Node.js" },
            { id: 4, name: "D3.js" },
        ],
        client: "FinanceFlow Corp.",
    },
    {
        id: 5,
        image: "/images/working.jpg",
        type: "Web Design & Development",
        year: 2022,
        title: "EduLearn Learning Platform",
        description: "Online learning platform with interactive live streaming and quiz features.",
        techStack: [
            { id: 1, name: "React" },
            { id: 2, name: "Node.js" },
            { id: 3, name: "MongoDB" },
            { id: 4, name: "Socket.io" },
            { id: 5, name: "AWS" },
        ],
        client: "EduLearn Indonesia",
    },
    {
        id: 6,
        image: "/images/working.jpg",
        type: "Mobile App",
        year: 2023,
        title: "FitTracker Mobile App",
        description: "Fitness Tracking Application with AI Personal Trainer and Community.",
        techStack: [
            { id: 1, name: "Flutter" },
            { id: 2, name: "Node.js" },
            { id: 3, name: "MongoDB" },
            { id: 4, name: "Socket.io" },
            { id: 5, name: "AWS" },
        ],
        client: "FitLife",
    },
    {
        id: 7,
        image: "/images/working.jpg",
        type: "SEO & Digital Marketing",
        year: 2024,
        title: "BoostBiz SEO Campaign",
        description: "Comprehensive SEO and digital marketing campaign for small businesses.",
        techStack: [
            { id: 1, name: "Google Ads" },
            { id: 2, name: "Facebook Ads" },
            { id: 3, name: "SEO" },
            { id: 4, name: "Content Marketing" },
            { id: 5, name: "Email Marketing" },
        ],
        client: "BoostBiz",
    },
    {
        id: 8,
        image: "/images/working.jpg",
        type: "UX Research & Consulting",
        year: 2024,
        title: "User Experience Research for E-commerce",
        description: "In-depth UX research and analysis for improving e-commerce platforms.",
        techStack: [
            { id: 1, name: "User Interviews" },
            { id: 2, name: "Usability Testing" },
            { id: 3, name: "Figma" },
            { id: 4, name: "Adobe XD" },
        ],
        client: "E-commerce Inc.",
    },
    {
        id: 9,
        image: "/images/working.jpg",
        type: "Brand Identity Design",
        year: 2023,
        title: "TravelMate Brand Identity",
        description: "Creating a fresh brand identity for a travel agency focusing on adventure tourism.",
        techStack: [
            { id: 1, name: "Adobe Illustrator" },
            { id: 2, name: "Adobe Photoshop" },
            { id: 3, name: "Figma" },
            { id: 4, name: "Canva" },
        ],
        client: "TravelMate",
    },
    {
        id: 10,
        image: "/images/working.jpg",
        type: "Mobile App",
        year: 2022,
        title: "FoodieFinds Mobile App",
        description: "A social dining app that connects food enthusiasts and local eateries.",
        techStack: [
            { id: 1, name: "React Native" },
            { id: 2, name: "Node.js" },
            { id: 3, name: "Firebase" },
        ],
        client: "FoodieFinds LLC",
    },
    {
        id: 11,
        image: "/images/working.jpg",
        type: "SEO & Digital Marketing",
        year: 2023,
        title: "HealthPlus Digital Marketing",
        description: "Digital marketing strategy and execution for a healthcare services provider.",
        techStack: [
            { id: 1, name: "Google Ads" },
            { id: 2, name: "SEO" },
            { id: 3, name: "Content Marketing" },
            { id: 4, name: "Social Media Marketing" },
        ],
        client: "HealthPlus",
    },
    {
        id: 12,
        image: "/images/working.jpg",
        type: "UX Research & Consulting",
        year: 2022,
        title: "FinTech App UX Overhaul",
        description: "Comprehensive UX research and redesign for a fintech mobile application.",
        techStack: [
            { id: 1, name: "User Interviews" },
            { id: 2, name: "Usability Testing" },
            { id: 3, name: "Figma" },
            { id: 4, name: "Adobe XD" },
        ],
        client: "FinTech Inc.",
    }
]